### ISSUE TITLE
heroku 404

### ISSUE THREAD

**Issue by wanghaisheng** [Evil0ctal/TikTokDownloader_PyWebIO#4]
我还尝试把add_url_rule 从 main里拿出来 并且添加route
两种方法下  / 都是404

**Comment by wanghaisheng** [comment]
似乎和这里没有关系 
我把Procfile 改成这样就没事了
web: python  TikTok_ZH.py --port=$PORT

**Comment by Evil0ctal** [comment]
> 似乎和这里没有关系 我把Procfile 改成这样就没事了 web: python TikTok_ZH.py --port=$PORT

我刚刚修改了Profile，但是Heroku报错了，之前主页会报错404，但是API可以正常访问，我再去研究一下，感谢你的反馈！

2022-03-07T03:12:12.252086+00:00 heroku[web.1]: Starting process with command `python TikTok_ZH.py --port=58233`
2022-03-07T03:12:15.154874+00:00 heroku[web.1]: State changed from starting to crashed
2022-03-07T03:12:14.806005+00:00 app[web.1]:  * Serving Flask app 'TikTok_ZH' (lazy loading)
2022-03-07T03:12:14.806045+00:00 app[web.1]:  * Environment: production
2022-03-07T03:12:14.806046+00:00 app[web.1]:    WARNING: This is a development server. Do not use it in a production deployment.
2022-03-07T03:12:14.806046+00:00 app[web.1]:    Use a production WSGI server instead.
2022-03-07T03:12:14.806046+00:00 app[web.1]:  * Debug mode: off
2022-03-07T03:12:14.806337+00:00 app[web.1]: Traceback (most recent call last):
2022-03-07T03:12:14.806340+00:00 app[web.1]:   File "/app/TikTok_ZH.py", line 605, in <module>
2022-03-07T03:12:14.806895+00:00 app[web.1]:     app.run(host='0.0.0.0', port=80)
2022-03-07T03:12:14.806899+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 920, in run
2022-03-07T03:12:14.807203+00:00 app[web.1]:     run_simple(t.cast(str, host), port, self, **options)
2022-03-07T03:12:14.807215+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/werkzeug/serving.py", line 1010, in run_simple
2022-03-07T03:12:14.807524+00:00 app[web.1]:     inner()
2022-03-07T03:12:14.807527+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/werkzeug/serving.py", line 950, in inner
2022-03-07T03:12:14.807825+00:00 app[web.1]:     srv = make_server(
2022-03-07T03:12:14.807827+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/werkzeug/serving.py", line 782, in make_server
2022-03-07T03:12:14.808081+00:00 app[web.1]:     return ThreadedWSGIServer(
2022-03-07T03:12:14.808084+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/werkzeug/serving.py", line 688, in __init__
2022-03-07T03:12:14.808310+00:00 app[web.1]:     super().__init__(server_address, handler)  # type: ignore
2022-03-07T03:12:14.808312+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/socketserver.py", line 452, in __init__
2022-03-07T03:12:14.808577+00:00 app[web.1]:     self.server_bind()
2022-03-07T03:12:14.808579+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/http/server.py", line 138, in server_bind
2022-03-07T03:12:14.808720+00:00 app[web.1]:     socketserver.TCPServer.server_bind(self)
2022-03-07T03:12:14.808731+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/socketserver.py", line 466, in server_bind
2022-03-07T03:12:14.808969+00:00 app[web.1]:     self.socket.bind(self.server_address)
2022-03-07T03:12:14.809004+00:00 app[web.1]: PermissionError: [Errno 13] Permission denied
2022-03-07T03:12:15.060576+00:00 heroku[web.1]: Process exited with status 1

**Comment by wanghaisheng** [comment]
```
    app.add_url_rule('/', 'webio_view', webio_view(main),
                     methods=['GET', 'POST', 'OPTIONS'])

    if (os.environ.get('PORT')):
        port = int(os.environ.get('PORT'))
    else:
        port = 5000
        
    app.run(host='0.0.0.0', port=port)
```
我那个profile配合上面的这个 应该就可以？你试试看

**Comment by Evil0ctal** [comment]
> ```
>     app.add_url_rule('/', 'webio_view', webio_view(main),
>                      methods=['GET', 'POST', 'OPTIONS'])
> 
>     if (os.environ.get('PORT')):
>         port = int(os.environ.get('PORT'))
>     else:
>         port = 5000
>         
>     app.run(host='0.0.0.0', port=port)
> ```
> 
> 我那个profile配合上面的这个 应该就可以？你试试看

感谢，刚刚修改了代码，现在可以正常访问了，但是TikTok无法解析，可能是Heroku服务器的问题，抖音可正常解析。

**Comment by wanghaisheng** [comment]
@Evil0ctal 还好像真是服务器网络。。。我也复现了 咋办
